URLS:
    BASE_URL: "https://fantasy.premierleague.com/api/"
    GENERAL_INFO: "bootstrap-static/"
    FIXTURES: "fixtures/"
    FIXTURES_BY_GAMEWEEK: "fixtures/?event={event_id}"
    PLAYER_DATA: "element-summary/{element_id}/"
    GAMEWEEK_DATA: "event/{event_id}/live/"
    MANAGER_SUMMARY: "entry/{manager_id}/"
    MANAGER_HISTORY: "entry/{manager_id}/history/"
    MANAGER_TRANSFERS: "entry/{manager_id}/transfers/"
    CURRENT_GAMEWEEK_TRANSFERS: "entry/{manager_id}/transfers-latest/"
    CLASSIC_LEAGUE_STANDINGS: "leagues-classic/{league_id}/standings/"
    HEAD_TO_HEAD_LEAGUE_STANDINGS: "leagues-h2h-matches/league/{league_id}/"
    MANAGER_TEAM: "my-team/{manager_id}/"
    MANAGER_TEAM_BY_GAMEWEEK: "entry/{manager_id}/event/{event_id}/picks/"
    EVENT_STATUS: "event-status/"
    DREAM_TEAM: "dream-team/{event_id}/"
    SET_PIECE_NOTES: "team/set-piece-notes/"
    MANAGER_DATA: "me/"
    LEAGUE_CUP_STATUS: "league/{league_id}/cup-status/"
    MOST_VALUABLE_TEAMS: "stats/most-valuable-teams/"
    BEST_LEAGUES: "stats/best-leagues/" 
