# Generated by Django 4.2.16 on 2025-09-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setpiecenote',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
