# Generated by Django 4.2.16 on 2025-10-05 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_sofasportfixture_sofasportheatmap_sofasportlineup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SofasportPlayerAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sofasport_player_id', models.BigIntegerField(help_text='SofaSport player ID from API')),
                ('attacking', models.IntegerField(blank=True, help_text='Attacking ability rating (0-100)', null=True)),
                ('technical', models.IntegerField(blank=True, help_text='Technical skill rating (0-100)', null=True)),
                ('tactical', models.IntegerField(blank=True, help_text='Tactical awareness rating (0-100)', null=True)),
                ('defending', models.IntegerField(blank=True, help_text='Defensive ability rating (0-100)', null=True)),
                ('creativity', models.IntegerField(blank=True, help_text='Creativity/playmaking rating (0-100)', null=True)),
                ('position', models.CharField(blank=True, help_text='Position for these attributes (F, M, D, G)', max_length=10, null=True)),
                ('year_shift', models.IntegerField(default=0, help_text='0 = current season, negative = previous seasons')),
                ('is_average', models.BooleanField(default=False, help_text='True if from averageAttributeOverviews (career average)')),
                ('raw_data', models.JSONField(default=dict, help_text='Complete API response')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When attributes were last fetched')),
                ('athlete', models.ForeignKey(help_text='Link to FPL athlete', on_delete=django.db.models.deletion.CASCADE, related_name='sofasport_attributes', to='etl.athlete')),
            ],
            options={
                'db_table': 'sofasport_player_attributes',
                'ordering': ['athlete', '-year_shift'],
                'abstract': False,
                'indexes': [models.Index(fields=['athlete'], name='sofasport_p_athlete_dba66f_idx'), models.Index(fields=['sofasport_player_id'], name='sofasport_p_sofaspo_257548_idx'), models.Index(fields=['year_shift'], name='sofasport_p_year_sh_79893c_idx'), models.Index(fields=['position'], name='sofasport_p_positio_0d86b2_idx')],
                'unique_together': {('athlete', 'year_shift', 'is_average')},
            },
        ),
    ]
