# Generated by Django 4.2.27 on 2025-12-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_wildcardsimulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top100Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_id', models.BigIntegerField(help_text='FPL manager entry ID')),
                ('game_week', models.PositiveIntegerField(help_text='Gameweek when this snapshot was taken')),
                ('player_name', models.CharField(help_text="Manager's display name", max_length=255)),
                ('entry_name', models.CharField(help_text='Team name', max_length=255)),
                ('rank', models.PositiveIntegerField(help_text='Rank in the league at this gameweek')),
                ('last_rank', models.PositiveIntegerField(blank=True, help_text='Previous rank', null=True)),
                ('total_points', models.IntegerField(default=0, help_text='Total points for the season')),
                ('event_total', models.IntegerField(default=0, help_text='Points scored this gameweek')),
                ('active_chip', models.CharField(blank=True, help_text='Chip used this GW (wildcard, freehit, bboost, 3xc)', max_length=50, null=True)),
                ('bank', models.IntegerField(default=0, help_text='Money in bank (in tenths, e.g., 5 = £0.5m)')),
                ('team_value', models.IntegerField(default=0, help_text='Team value (in tenths)')),
            ],
            options={
                'db_table': 'top100_managers',
                'ordering': ['-game_week', 'rank'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Top100Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_week', models.PositiveIntegerField(help_text='Gameweek for this pick')),
                ('position', models.PositiveIntegerField(help_text='Squad position (1-11 = starting, 12-15 = bench)')),
                ('is_captain', models.BooleanField(default=False)),
                ('is_vice_captain', models.BooleanField(default=False)),
                ('multiplier', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'top100_picks',
                'ordering': ['manager', 'position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Top100Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_week', models.PositiveIntegerField(help_text='Gameweek', unique=True)),
                ('manager_count', models.PositiveIntegerField(default=100, help_text='Number of managers tracked')),
                ('league_id', models.CharField(default='314', help_text='League ID used', max_length=50)),
                ('average_points', models.DecimalField(blank=True, decimal_places=2, help_text='Average points scored by top managers this GW', max_digits=7, null=True)),
                ('highest_points', models.IntegerField(blank=True, null=True)),
                ('lowest_points', models.IntegerField(blank=True, null=True)),
                ('template_team', models.JSONField(default=list, help_text='Most common starting 11 with ownership percentage')),
                ('template_squad', models.JSONField(default=list, help_text='Most common 22 players (15 squad + bench)')),
                ('most_captained', models.JSONField(default=list, help_text='Top captaincy picks [{athlete_id, count, percentage}]')),
                ('chip_usage', models.JSONField(default=dict, help_text='Chip usage counts {wildcard: n, freehit: n, bboost: n, 3xc: n}')),
                ('most_transferred_in', models.JSONField(default=list, help_text='Most transferred in players this GW')),
                ('most_transferred_out', models.JSONField(default=list, help_text='Most transferred out players this GW')),
            ],
            options={
                'db_table': 'top100_summaries',
                'ordering': ['-game_week'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Top100Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_week', models.PositiveIntegerField(help_text='Gameweek when transfer was made')),
                ('element_in_cost', models.IntegerField(help_text='Purchase price (in tenths)')),
                ('element_out_cost', models.IntegerField(help_text='Sale price (in tenths)')),
                ('transfer_time', models.DateTimeField(blank=True, help_text='When transfer was made', null=True)),
            ],
            options={
                'db_table': 'top100_transfers',
                'ordering': ['-game_week', '-transfer_time'],
                'abstract': False,
            },
        ),
        migrations.RenameIndex(
            model_name='wildcardsimulation',
            new_name='wildcard_si_code_726e58_idx',
            old_name='wildcard_si_code_idx',
        ),
        migrations.RenameIndex(
            model_name='wildcardsimulation',
            new_name='wildcard_si_created_5385d6_idx',
            old_name='wildcard_si_created_idx',
        ),
        migrations.RenameIndex(
            model_name='wildcardsimulation',
            new_name='wildcard_si_is_save_992ed5_idx',
            old_name='wildcard_si_is_save_idx',
        ),
        migrations.AlterField(
            model_name='wildcardsimulation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='top100transfer',
            name='element_in',
            field=models.ForeignKey(help_text='Player transferred in', on_delete=django.db.models.deletion.CASCADE, related_name='top100_transfers_in', to='etl.athlete'),
        ),
        migrations.AddField(
            model_name='top100transfer',
            name='element_out',
            field=models.ForeignKey(help_text='Player transferred out', on_delete=django.db.models.deletion.CASCADE, related_name='top100_transfers_out', to='etl.athlete'),
        ),
        migrations.AddField(
            model_name='top100transfer',
            name='manager',
            field=models.ForeignKey(help_text='Link to manager snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='etl.top100manager'),
        ),
        migrations.AddField(
            model_name='top100pick',
            name='athlete',
            field=models.ForeignKey(help_text='The player selected', on_delete=django.db.models.deletion.CASCADE, related_name='top100_picks', to='etl.athlete'),
        ),
        migrations.AddField(
            model_name='top100pick',
            name='manager',
            field=models.ForeignKey(help_text='Link to manager snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='etl.top100manager'),
        ),
        migrations.AddIndex(
            model_name='top100manager',
            index=models.Index(fields=['game_week'], name='top100_mana_game_we_4e6eba_idx'),
        ),
        migrations.AddIndex(
            model_name='top100manager',
            index=models.Index(fields=['entry_id'], name='top100_mana_entry_i_39af95_idx'),
        ),
        migrations.AddIndex(
            model_name='top100manager',
            index=models.Index(fields=['game_week', 'rank'], name='top100_mana_game_we_bbd774_idx'),
        ),
        migrations.AddConstraint(
            model_name='top100manager',
            constraint=models.UniqueConstraint(fields=('entry_id', 'game_week'), name='unique_manager_gameweek'),
        ),
        migrations.AddIndex(
            model_name='top100transfer',
            index=models.Index(fields=['game_week'], name='top100_tran_game_we_3a2397_idx'),
        ),
        migrations.AddIndex(
            model_name='top100transfer',
            index=models.Index(fields=['element_in'], name='top100_tran_element_afabdf_idx'),
        ),
        migrations.AddIndex(
            model_name='top100transfer',
            index=models.Index(fields=['element_out'], name='top100_tran_element_338d83_idx'),
        ),
        migrations.AddIndex(
            model_name='top100transfer',
            index=models.Index(fields=['game_week', 'element_in'], name='top100_tran_game_we_3b1a03_idx'),
        ),
        migrations.AddIndex(
            model_name='top100pick',
            index=models.Index(fields=['game_week'], name='top100_pick_game_we_35b0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='top100pick',
            index=models.Index(fields=['athlete'], name='top100_pick_athlete_1a0028_idx'),
        ),
        migrations.AddIndex(
            model_name='top100pick',
            index=models.Index(fields=['game_week', 'athlete'], name='top100_pick_game_we_78623e_idx'),
        ),
        migrations.AddIndex(
            model_name='top100pick',
            index=models.Index(fields=['is_captain'], name='top100_pick_is_capt_38b73c_idx'),
        ),
        migrations.AddConstraint(
            model_name='top100pick',
            constraint=models.UniqueConstraint(fields=('manager', 'athlete'), name='unique_manager_athlete_pick'),
        ),
    ]
