# Generated by Django 4.2.27 on 2025-12-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_top100_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofasportfixture',
            name='away_team_name',
            field=models.CharField(blank=True, help_text='Away team name from SofaSport', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sofasportfixture',
            name='competition',
            field=models.CharField(choices=[('PL', 'Premier League'), ('UCL', 'UEFA Champions League'), ('UEL', 'UEFA Europa League'), ('UECL', 'UEFA Conference League'), ('FAC', 'FA Cup'), ('EFL', 'EFL Cup'), ('OTHER', 'Other')], db_index=True, default='PL', help_text='Competition code (PL, UCL, UEL, FAC, EFL, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='sofasportfixture',
            name='competition_name',
            field=models.CharField(default='Premier League', help_text='Full competition name', max_length=100),
        ),
        migrations.AddField(
            model_name='sofasportfixture',
            name='home_team_name',
            field=models.CharField(blank=True, help_text='Home team name from SofaSport', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sofasportfixture',
            name='sofasport_season_id',
            field=models.BigIntegerField(blank=True, help_text='SofaSport seasons_id', null=True),
        ),
        migrations.AddField(
            model_name='sofasportfixture',
            name='sofasport_tournament_id',
            field=models.BigIntegerField(blank=True, help_text='SofaSport unique_tournament_id', null=True),
        ),
        migrations.AlterField(
            model_name='sofasportfixture',
            name='away_team',
            field=models.ForeignKey(blank=True, help_text='FPL away team (if mappable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sofasport_away_fixtures', to='etl.team'),
        ),
        migrations.AlterField(
            model_name='sofasportfixture',
            name='fixture',
            field=models.ForeignKey(blank=True, help_text='Link to FPL fixture (null for non-PL matches)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sofasport_fixtures', to='etl.fixture'),
        ),
        migrations.AlterField(
            model_name='sofasportfixture',
            name='home_team',
            field=models.ForeignKey(blank=True, help_text='FPL home team (if mappable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sofasport_home_fixtures', to='etl.team'),
        ),
        migrations.AddIndex(
            model_name='sofasportfixture',
            index=models.Index(fields=['competition'], name='sofasport_f_competi_043447_idx'),
        ),
        migrations.AddIndex(
            model_name='sofasportfixture',
            index=models.Index(fields=['kickoff_time'], name='sofasport_f_kickoff_bd9531_idx'),
        ),
    ]
