# Generated by Django 4.2.27 on 2025-12-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_add_competition_fields_to_sofasportfixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_odds', models.DecimalField(blank=True, decimal_places=2, help_text='Decimal odds for home win', max_digits=6, null=True)),
                ('draw_odds', models.DecimalField(blank=True, decimal_places=2, help_text='Decimal odds for draw', max_digits=6, null=True)),
                ('away_odds', models.DecimalField(blank=True, decimal_places=2, help_text='Decimal odds for away win', max_digits=6, null=True)),
                ('prev_home_odds', models.DecimalField(blank=True, decimal_places=2, help_text='Previous home odds for arrow display', max_digits=6, null=True)),
                ('prev_draw_odds', models.DecimalField(blank=True, decimal_places=2, help_text='Previous draw odds', max_digits=6, null=True)),
                ('prev_away_odds', models.DecimalField(blank=True, decimal_places=2, help_text='Previous away odds', max_digits=6, null=True)),
                ('over_under_line', models.DecimalField(blank=True, decimal_places=1, help_text='Over/Under line (e.g., 2.5 goals)', max_digits=3, null=True)),
                ('over_odds', models.DecimalField(blank=True, decimal_places=2, help_text='Decimal odds for over', max_digits=6, null=True)),
                ('under_odds', models.DecimalField(blank=True, decimal_places=2, help_text='Decimal odds for under', max_digits=6, null=True)),
                ('prev_over_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('prev_under_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('btts_yes_odds', models.DecimalField(blank=True, decimal_places=2, help_text='Decimal odds for both teams to score', max_digits=6, null=True)),
                ('btts_no_odds', models.DecimalField(blank=True, decimal_places=2, help_text='Decimal odds for not both teams to score', max_digits=6, null=True)),
                ('prev_btts_yes_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('prev_btts_no_odds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('provider_id', models.CharField(default='1', help_text='SofaSport bookmaker provider ID', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When odds were last fetched')),
                ('fixture', models.OneToOneField(help_text='Link to SofaSport fixture', on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='etl.sofasportfixture')),
            ],
            options={
                'verbose_name_plural': 'Fixture Odds',
                'db_table': 'fixture_odds',
                'ordering': ['-last_updated'],
                'abstract': False,
                'indexes': [models.Index(fields=['fixture'], name='fixture_odd_fixture_6ca725_idx'), models.Index(fields=['last_updated'], name='fixture_odd_last_up_9b1983_idx')],
            },
        ),
    ]
