# Generated by Django 4.2.27 on 2026-01-12 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0009_add_fixture_odds'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthletePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_week', models.PositiveIntegerField()),
                ('predicted_points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('athlete', models.ForeignKey(db_column='athlete_id', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='etl.athlete')),
            ],
            options={
                'db_table': 'athlete_predictions',
                'abstract': False,
                'indexes': [models.Index(fields=['athlete'], name='athlete_pre_athlete_a2d897_idx'), models.Index(fields=['game_week'], name='athlete_pre_game_we_026faf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='athleteprediction',
            constraint=models.UniqueConstraint(fields=('athlete', 'game_week'), name='unique_athlete_gameweek_prediction'),
        ),
    ]
