# Generated by Django 4.2.29 on 2026-03-13 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0010_athleteprediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprediction',
            name='assist_prob',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='athleteprediction',
            name='bonus_prob',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='athleteprediction',
            name='clean_sheet_prob',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='athleteprediction',
            name='goal_prob',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField(db_index=True)),
                ('cost', models.IntegerField()),
                ('transfers_in_total', models.IntegerField()),
                ('transfers_out_total', models.IntegerField()),
                ('transfers_in_event', models.IntegerField(default=0)),
                ('transfers_out_event', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('form', models.CharField(default='0.0', max_length=10)),
                ('selected_by_percent', models.CharField(default='0.0', max_length=10)),
                ('athlete', models.ForeignKey(db_column='athlete_id', on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='etl.athlete')),
            ],
            options={
                'db_table': 'price_snapshots',
                'indexes': [models.Index(fields=['snapshot_time'], name='price_snaps_snapsho_c61cf5_idx'), models.Index(fields=['athlete', 'snapshot_time'], name='price_snaps_athlete_054c6d_idx')],
                'unique_together': {('athlete', 'snapshot_time')},
            },
        ),
    ]
