FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=example
ENV POSTGRES_DB=fpl

# Define the volume
VOLUME /var/lib/postgresql/data

# Expose PostgreSQL default port
EXPOSE 5432